name: Build RPMs

on:
  push:
    branches:
      - main
    paths:
      - 'rpm/harbour-audiocut.spec'

env:
  OS_VERSION: 4.4.0.68

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build App
    strategy:
      matrix:
        arch: ['armv7hl']

    steps:
    - uses: actions/checkout@v2

    - name: Prepare
      run: docker pull coderus/sailfishos-platform-sdk:$OS_VERSION && mkdir output

    - name: Build ${{ matrix.arch }}
      run: docker run --rm --privileged -v $PWD:/share coderus/sailfishos-platform-sdk:$OS_VERSION /bin/bash -c "
            mkdir -p build ;
            cd build ;
            cp -r /share/* . ;
            mb2 -t SailfishOS-$OS_VERSION-${{ matrix.arch }} build ;
            sudo cp -r RPMS/*.rpm /share/output"
      
    - name: Upload RPM (${{ matrix.arch }})
      uses: actions/upload-artifact@v2
      with:
        name: rpm-${{ matrix.arch }}
        path: output
  release:
    name: Release
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download armv7hl
        uses: actions/download-artifact@v2
        with:
          name: rpm-armv7hl
        continue-on-error: true
      - name: Extract Version Name
        run: |
          echo "VERSION_NAME=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV
      - name: Extract Version Comment
        run: |
          echo "TAG_MESSAGE=$(git tag -l --format='%(contents:subject)'${$VERSION_NAME})" >> $GITHUB_ENV
      - name: Create a Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ env.VERSION_NAME }}
          draft: false
          prerelease: false
          body: ${{ env.TAG_MESSAGE }} This release was autogenerated.
          files: '*.rpm'
